version: '3.3'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/my_backend/src
    env_file:
      - ./.env
    ports:
      - 3000:3000
    command: 'yarn start:dev'

  my_database_local:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
