steps:
  - name: docker/compose:1.29.0 # docker-compose
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - build

  - name: docker/compose:1.29.0 # docker-compose
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - push

  - name: gcr.io/cloud-builders/kubectl # kubectl
    args:
      - set
      - image
      - deployment/mybackend3
      - my-backend-sha256-1=asia.gcr.io/codecamp-308601/my_backend:13
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-3
